on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: node:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - run: |
          ls -la
          echo "test"

