services:
  desec:
    container_name: desec
    image: git.devdoes.work/devaine/scripts:desec
    platform: "linux/arm64"
    environment:
      - DESEC_TOKEN=${DESEC_TOKEN}
      - CURRENT_DOMAIN=${CURRENT_DOMAIN}
